spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: 524013659?Ln
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
